- hosts: all    
  become: yes
  tasks:
  - name:Install Docker
    yum: name=docker state=present update _cache=true
  - name: Start Docker
    service: name=docker state=started
   - name: Copy a new index.htmlfile into place, backing up
     copy:
        src: /home/ec2-user/index.html
        dest: /var/www/html/index.html
        owner: ec2-user
        group: ec2-user
        mode: '0644'
        backup: yes
     - name: Copy a new DockerFile
       copy:
        src: /home/ec2-user/index.html
        dest: /var/www/html/index.html
        owner: ec2-user
        group: ec2-user
        mode: '0644'
        backup: yes
     - name: /Build a docker image
       command: docker build -t web/home/ec2-user
     - name: Run a container
       command: docker container run -d -p 80:80 --name mynewapp web
